#! /bin/sh
### BEGIN INIT INFO
# Provides: firecontrol
# Required-Start: $syslog
# Required-Stop: $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: firecontrol script
# Description: based on https://tutorials-raspberrypi.de/raspberry-pi-autostart-programm-skript/
### END INIT INFO
 
case "$1" in
    start)
        echo "start firecontrol"
        python3 /home/{YOUR_USER}/firecontrol.py
        ;;
    stop)
        echo "stop firecontrol"
        pkill -f "/home/{YOUR_USER}/firecontrol.py"
        ;;
    *)
        echo "Use: firecontrol {start|stop}"
        exit 1
        ;;
esac
 
exit 0
